Pop up
29td/My-First-Portfolio pull request #14
Opened 2022-06-22 16:25 UTC by 29td

Create a pop up window

2022-06-24 14:58 UTC, KayLemba requested changes
Hi @29td   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-24 15:08 UTC, KayLemba requested changes
Hi @29td   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-24 15:08 UTC, KayLemba commented on index.html
> +                <button id="ject1" class="button1 window" type="submit">See Project</button>
While you did a good job implementing the pop up window of the project. Your mobile pop up window section needs some minor adjustments.

- Kindly repostion your cancel button (X) to the right hand side of the pop up container please kindly folllow the design on figma 
- Kindly get rid of the horizontal overflow.
- Please resize your "See live" and "See Source" buttons for them to properly fit the mobile section pop up window.
- Please use correct font size 
 This is how you design looks.
![Screenshot from 2022-06-24 18-37-02](https://user-images.githubusercontent.com/79506105/175563704-8243bb51-14fb-4cd4-9914-2a1325e728d8.png)


![Screenshot from 2022-06-24 18-37-49](https://user-images.githubusercontent.com/79506105/175563807-2c501f55-e0a6-48c2-99ac-fd29d06f16ec.png)

Please follow this  Figma design:
![Screenshot from 2022-06-24 18-56-35](https://user-images.githubusercontent.com/79506105/175563955-8531c046-800c-4e7d-9769-56402f5e9e6c.png)

2022-06-24 15:45 UTC, 29td commented
@KayLemba maybe your screen sizing for the desktop part is not correct because everything is working fine on my end i can even share a video as proof

2022-06-24 15:54 UTC, 29td commented
![Screenshot 2022-06-24 174852](https://user-images.githubusercontent.com/93027816/175571790-7c925a70-a4df-4552-a2f8-923101f5b388.png)
@KayLemba _ The width and height you used next to responsive is not correct. remember the max-width is suppose to be 780 not a 1000 or more_

2022-06-24 16:54 UTC, zieeco requested changes
Hi @29td,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 16:54 UTC, zieeco commented on index.html
> +                <button id="ject1" class="button1 window" type="submit">See Project</button>
- [ ] Hey, As requested by the previous reviewer, kindly address the issue with the horizontal scroll effect as this is too obvious to be overlooked and this behavior doesn't improve the user experience. 
- [ ] Also, your popup only shows on the first and second projects which are supposed to show on all projects when the see project button is clicked.
- [ ] Please also fix your pop up so it doesn't overlap to cover other content in your design.
- [ ] Kindly watch the video below to see your popup in action:

https://user-images.githubusercontent.com/59397159/175606081-8270069d-5bed-4643-82b2-bda40b30167b.mp4

2022-06-25 11:01 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi team  

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 
- [ optional] kindly make the popups responsive to all the screen sizes 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 11:32 UTC, merged